---
title: "viz and eda"
author: "Rene Chi"
date: "2025-09-25"
output: github_document
---

## R Markdown

```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
```

import the weather data

```{r}
data("weather_df")
```
making our first plot
```{r}
ggplot(data = weather_df, mapping = aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```
check that some rows are missing
```{r}
weather_df |> 
  filter(is.na(tmax))
```
## Fancier scatterplots!

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)
```
use faceting real quick
```{r}
weather_df |> 
  ggplot(aes(x= tmin, y= tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)

weather_df |> 
  ggplot(aes(x= tmin, y= tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(name ~.)
```
let's make a more scatterplot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(.~ name)
```
Learning assessment
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax * (9/5) + 32,
    tmin_fahr = tmin * (9/5) + 32
  ) |> 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
    geom_point() +
    geom_smooth(se = FALSE, method = "lm")
```

## Small things

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
#  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(color = "purple")
```
## Univariate plot
```{r}
weather_df |> 
  ggplot(aes(x = tmin)) +
  geom_histogram(color = "white", fill = "red")

```
 
```{r}
weather_df |> 
  ggplot(aes(x = tmin, color = name)) +
  geom_histogram()

weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() +
  facet_grid(name ~.)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = 0.2)
```

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmin)) +
  geom_boxplot(aes(fill = name))
```

violin plots
```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmin)) +
  geom_violin()
```

ridge plot

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = name)) +
  geom_density_ridges()
```
Assessment
```{r}
weather_df |> 
  filter(prcp > 5, prcp < 1000) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)
```

